"""Per-league market definitions for the training pipeline."""

ALL_MARKETS: dict[str, list[str]] = {
    "NFL": [
        "targets",
        "carries",
        "attempts",
        "passing yards",
        "rushing yards",
        "receiving yards",
        "yards",
        "qb yards",
        "fantasy points prizepicks",
        "fantasy points underdog",
        "passing tds",
        "tds",
        "rushing tds",
        "receiving tds",
        "qb tds",
        "completions",
        "receptions",
        "interceptions",
        "sacks taken",
        "passing first downs",
        # "first downs",
        # "completion percentage"
    ],
    "NBA": [
        "MIN",
        "PTS",
        "REB",
        "AST",
        "PRA",
        "PR",
        "RA",
        "PA",
        "FG3M",
        "fantasy points prizepicks",
        "FG3A",
        "FTM",
        "FGM",
        "FGA",
        "STL",
        "BLK",
        "BLST",
        "TOV",
        "OREB",
        "DREB",
        "PF",
    ],
    "WNBA": [
        "MIN",
        "AST",
        "FG3M",
        "PA",
        "PR",
        "PTS",
        "RA",
        "REB",
        "OREB",
        "DREB",
        "FGA",
        "BLK",
        "STL",
        "BLST",
        "TOV",
        "FTM",
        "PRA",
        "fantasy points prizepicks",
    ],
    "MLB": [
        "plateAppearances",
        "pitches thrown",
        "pitching outs",
        "pitcher strikeouts",
        "hits allowed",
        "runs allowed",
        "walks allowed",
        # "1st inning runs allowed",
        # "1st inning hits allowed",
        "hitter fantasy score",
        "pitcher fantasy score",
        "hitter fantasy points underdog",
        "pitcher fantasy points underdog",
        "hits+runs+rbi",
        "total bases",
        "walks",
        "stolen bases",
        "hits",
        "runs",
        "rbi",
        "batter strikeouts",
        "singles",
        "doubles",
        "home runs",
    ],
    "NHL": [
        "timeOnIce",
        "shotsAgainst",
        "saves",
        "shots",
        "points",
        "goalsAgainst",
        "goalie fantasy points underdog",
        "skater fantasy points underdog",
        "blocked",
        "powerPlayPoints",
        "sogBS",
        # "fantasy points prizepicks",
        "hits",
        "goals",
        "assists",
        "faceOffWins",
    ],
}
