"""Declarative model-strategy registry, artifact identity, and the Ship 75 sweep/confirm loop.

The public **library** surface — the strategy catalog, capability queries, CLI-arg builders, and
the artifact-identity contract — is re-exported here so callers import it as
``from sportstradamus.training.model_strategy import <name>``.

The two **orchestrators** are reached by their submodule path instead
(:mod:`sportstradamus.training.model_strategy.sweep` and
:mod:`sportstradamus.training.model_strategy.confirm`) so importing an identity or registry name
never pulls Optuna/subprocess into the prediction and report import paths, and so ``scorecard`` (which
imports the library surface) cannot form a package-init cycle with ``sweep``.
"""

from sportstradamus.training.model_strategy.identity import (
    ARTIFACT_SCHEMA_CSV_COLUMN,
    CORNER_FINGERPRINT_CSV_COLUMN,
    MATRIX_HASH_CSV_COLUMN,
    MODEL_STRATEGY_CSV_COLUMN,
    MODEL_STRATEGY_MODEL_KEY,
    SPLIT_FINGERPRINT_CSV_COLUMN,
    STRATEGY_CONTROLS_CSV_COLUMN,
    STRATEGY_IDENTITY_CSV_COLUMNS,
    STRATEGY_IMPLEMENTATION_CSV_COLUMN,
    STRATEGY_LEAGUE_CSV_COLUMN,
    STRATEGY_MARKET_CSV_COLUMN,
    STRATEGY_SIGNATURE_CSV_COLUMN,
    STRATEGY_STATUS_CSV_COLUMN,
    STRUCTURAL_STRATEGY_CSV_COLUMN,
    ArtifactIdentity,
    InactiveStrategyArtifactError,
    artifact_identity_columns,
    build_artifact_identity,
    resolve_report_identity,
    validate_model_recipe,
    validate_strategy_artifacts,
    validate_strategy_frame,
)
from sportstradamus.training.model_strategy.registry import (
    BASE_ARTIFACT_SCHEMA_VERSION,
    BASE_STRUCTURAL_STRATEGY,
    CAP_CONFIRM,
    CAP_DETERMINISTIC_TRAIN,
    CAP_FULL_HPO,
    CAP_SCORE,
    CAP_SERVE,
    SWEEP_CAPABILITIES,
    Applicability,
    CellContext,
    StrategySpec,
    artifact_namespace,
    canonical_json,
    controls_json,
    corner_fingerprint,
    distribution_class,
    get_strategy,
    meditate_command,
    parse_controls,
    registered_strategies,
    strategies_for_cell,
    strategy_cli_args,
    strategy_controls,
    strategy_full_hpo_cli_args,
    strategy_persistence_edits,
    validate_strategy_selection,
)

__all__ = [
    "ARTIFACT_SCHEMA_CSV_COLUMN",
    "BASE_ARTIFACT_SCHEMA_VERSION",
    "BASE_STRUCTURAL_STRATEGY",
    "CAP_CONFIRM",
    "CAP_DETERMINISTIC_TRAIN",
    "CAP_FULL_HPO",
    "CAP_SCORE",
    "CAP_SERVE",
    "CORNER_FINGERPRINT_CSV_COLUMN",
    "MATRIX_HASH_CSV_COLUMN",
    "MODEL_STRATEGY_CSV_COLUMN",
    "MODEL_STRATEGY_MODEL_KEY",
    "SPLIT_FINGERPRINT_CSV_COLUMN",
    "STRATEGY_CONTROLS_CSV_COLUMN",
    "STRATEGY_IDENTITY_CSV_COLUMNS",
    "STRATEGY_IMPLEMENTATION_CSV_COLUMN",
    "STRATEGY_LEAGUE_CSV_COLUMN",
    "STRATEGY_MARKET_CSV_COLUMN",
    "STRATEGY_SIGNATURE_CSV_COLUMN",
    "STRATEGY_STATUS_CSV_COLUMN",
    "STRUCTURAL_STRATEGY_CSV_COLUMN",
    "SWEEP_CAPABILITIES",
    "Applicability",
    "ArtifactIdentity",
    "CellContext",
    "InactiveStrategyArtifactError",
    "StrategySpec",
    "artifact_identity_columns",
    "artifact_namespace",
    "build_artifact_identity",
    "canonical_json",
    "controls_json",
    "corner_fingerprint",
    "distribution_class",
    "get_strategy",
    "meditate_command",
    "parse_controls",
    "registered_strategies",
    "resolve_report_identity",
    "strategies_for_cell",
    "strategy_cli_args",
    "strategy_controls",
    "strategy_full_hpo_cli_args",
    "strategy_persistence_edits",
    "validate_model_recipe",
    "validate_strategy_artifacts",
    "validate_strategy_frame",
    "validate_strategy_selection",
]
