"""Runtime body substitution for Fantasy Points v2 endpoints.

Catalog entries generated by :mod:`discover` use sentinel strings
in place of week / season values so the JSON-on-disk is static and
human-readable. At call time, this module:

1. Replaces ``"__WEEK_INT__"`` and ``"__SEASON_INT__"`` sentinels with
   the actual ``int`` values (FP's API rejects string ints for these
   fields).
2. Overrides ``context.weeks`` based on ``mode``:

   - ``weekly`` (default): ``{"REG": [week]}`` — just this week's data.
   - ``season_to_date``: ``{"REG": [1, 2, ..., week]}`` — cumulative
     through ``week`` (FP returns rows for whichever weeks exist).
   - ``postseason``: ``{"POST": [week]}`` — wildcard / divisional /
     conference championship / super bowl.

The substitution is a no-op for catalog bodies that don't contain the
sentinels (legacy entries), so it composes safely with the older
``{week}`` / ``{season}`` string substitution in :meth:`EndpointSpec.render_json_body`.
"""

from __future__ import annotations

import copy
from typing import Literal

# Sentinel strings used by discover.py inside otherwise-static JSON
# bodies. Distinct from the legacy ``{week}`` / ``{season}`` string
# placeholders because FP rejects string-typed week/season here.
_WEEK_INT_SENTINEL = "__WEEK_INT__"
_SEASON_INT_SENTINEL = "__SEASON_INT__"

Mode = Literal["weekly", "season_to_date", "postseason"]

# Default mode mirrors the typical UI default — the value the user
# selects via ``--mode`` on the CLI defaults to this.
DEFAULT_MODE: Mode = "weekly"


def substitute_runtime(
    body: dict,
    *,
    season: int,
    week: int,
    mode: Mode = DEFAULT_MODE,
) -> dict:
    """Render a catalog body for one (season, week, mode) call.

    Returns a deep copy — the catalog body itself is never mutated,
    so the same spec can be reused across the backfill loop without
    cross-talk between iterations.
    """
    out = copy.deepcopy(body)
    out = _replace_int_sentinels(out, season=season, week=week)
    _override_weeks(out, week=week, mode=mode)
    return out


def _replace_int_sentinels(node, *, season: int, week: int):
    if isinstance(node, dict):
        return {k: _replace_int_sentinels(v, season=season, week=week) for k, v in node.items()}
    if isinstance(node, list):
        return [_replace_int_sentinels(v, season=season, week=week) for v in node]
    if node == _WEEK_INT_SENTINEL:
        return int(week)
    if node == _SEASON_INT_SENTINEL:
        return int(season)
    return node


def _override_weeks(body: dict, *, week: int, mode: Mode) -> None:
    """Rewrite ``body['context']['weeks']`` in place per ``mode``.

    No-op when the body has no ``context`` or no ``weeks`` field —
    legacy entries that don't follow the v2 shape are passed through
    unchanged.
    """
    ctx = body.get("context")
    if not isinstance(ctx, dict) or "weeks" not in ctx:
        return
    if mode == "weekly":
        ctx["weeks"] = {"REG": [int(week)]}
    elif mode == "season_to_date":
        ctx["weeks"] = {"REG": list(range(1, int(week) + 1))}
    elif mode == "postseason":
        ctx["weeks"] = {"POST": [int(week)]}
