"""Capture-then-pin characterization for ``analysis.compute_individual_metrics``.

The function returns four frames (hist_stats / daily / calibration / roi) off a
shared prep; it has no other behavioral coverage (``test_analysis.py`` only
covers ``compute_book_brier_skill_score``) and the dashboard reflect path is its
sole caller. This pins all four exactly for a synthetic resolved-history slate
so the CC-16 decomposition stays byte-for-byte behavior-preserving.

Dates are today-anchored (REF-3 in every timeframe, REF-100 only in 6m/1y) so
timeframe-bucket membership and the 365-day window are stable across CI days.
The only date-bearing output column (``daily.Date``) is rebuilt from the same
offsets in-test. Generated from current output via /tmp/gen_individual_test.py;
the literals are frozen (a regression pin), not recomputed at assert time.
"""

from __future__ import annotations

from datetime import datetime, timedelta

import pandas as pd

from sportstradamus.analysis import compute_individual_metrics

REF = datetime.today().date()


def _d(days_ago: int) -> str:
    return str(REF - timedelta(days=days_ago))


def _build() -> pd.DataFrame:
    rows = [
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Over",
            "Model": 0.62,
            "Model P": 0.60,
            "Books": 0.55,
        },
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Under",
            "Model": 0.59,
            "Model P": 0.57,
            "Books": 0.53,
        },
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Under",
            "Result": "Under",
            "Model": 0.66,
            "Model P": 0.63,
            "Books": 0.58,
        },
        {
            "League": "NBA",
            "Market": "rebounds",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Over",
            "Model": 0.71,
            "Model P": 0.68,
            "Books": 0.60,
        },
        {
            "League": "WNBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Over",
            "Model": 0.60,
            "Model P": 0.59,
            "Books": 0.51,
        },
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Over",
            "Model": 0.55,
            "Model P": 0.54,
            "Books": 0.50,
        },
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(3),
            "Bet": "Over",
            "Result": "Push",
            "Model": 0.63,
            "Model P": 0.61,
            "Books": 0.56,
        },
        {
            "League": "NBA",
            "Market": "points",
            "Date": _d(100),
            "Bet": "Over",
            "Result": "Over",
            "Model": 0.64,
            "Model P": 0.61,
            "Books": 0.56,
        },
        {
            "League": "WNBA",
            "Market": "points",
            "Date": _d(100),
            "Bet": "Under",
            "Result": "Over",
            "Model": 0.68,
            "Model P": 0.65,
            "Books": 0.59,
        },
    ]
    return pd.DataFrame(rows)


_EXPECTED_HIST = [
    {
        "Period": "7d",
        "Split": "All",
        "Accuracy": 0.8,
        "Balance": 0.2,
        "LogLoss": 0.546,
        "Brier": 0.1785,
        "ROI": 0.5273,
        "Samples": 5,
    },
    {
        "Period": "7d",
        "Split": "All, Book Filtered",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "7d",
        "Split": "NBA",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "7d",
        "Split": "NBA - points",
        "Accuracy": 0.6667,
        "Balance": 0.3333,
        "LogLoss": 0.6056,
        "Brier": 0.2073,
        "ROI": 0.2727,
        "Samples": 3,
    },
    {
        "Period": "7d",
        "Split": "NBA - rebounds",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.3857,
        "Brier": 0.1024,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "7d",
        "Split": "WNBA",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "7d",
        "Split": "WNBA - points",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "30d",
        "Split": "All",
        "Accuracy": 0.8,
        "Balance": 0.2,
        "LogLoss": 0.546,
        "Brier": 0.1785,
        "ROI": 0.5273,
        "Samples": 5,
    },
    {
        "Period": "30d",
        "Split": "All, Book Filtered",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "30d",
        "Split": "NBA",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "30d",
        "Split": "NBA - points",
        "Accuracy": 0.6667,
        "Balance": 0.3333,
        "LogLoss": 0.6056,
        "Brier": 0.2073,
        "ROI": 0.2727,
        "Samples": 3,
    },
    {
        "Period": "30d",
        "Split": "NBA - rebounds",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.3857,
        "Brier": 0.1024,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "30d",
        "Split": "WNBA",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "30d",
        "Split": "WNBA - points",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "3m",
        "Split": "All",
        "Accuracy": 0.8,
        "Balance": 0.2,
        "LogLoss": 0.546,
        "Brier": 0.1785,
        "ROI": 0.5273,
        "Samples": 5,
    },
    {
        "Period": "3m",
        "Split": "All, Book Filtered",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "3m",
        "Split": "NBA",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5506,
        "Brier": 0.181,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "3m",
        "Split": "NBA - points",
        "Accuracy": 0.6667,
        "Balance": 0.3333,
        "LogLoss": 0.6056,
        "Brier": 0.2073,
        "ROI": 0.2727,
        "Samples": 3,
    },
    {
        "Period": "3m",
        "Split": "NBA - rebounds",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.3857,
        "Brier": 0.1024,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "3m",
        "Split": "WNBA",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "3m",
        "Split": "WNBA - points",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.5276,
        "Brier": 0.1681,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "6m",
        "Split": "All",
        "Accuracy": 0.7143,
        "Balance": 0.0,
        "LogLoss": 0.6106,
        "Brier": 0.2096,
        "ROI": 0.3636,
        "Samples": 7,
    },
    {
        "Period": "6m",
        "Split": "All, Book Filtered",
        "Accuracy": 0.6667,
        "Balance": 0.0,
        "LogLoss": 0.6244,
        "Brier": 0.2165,
        "ROI": 0.2727,
        "Samples": 6,
    },
    {
        "Period": "6m",
        "Split": "NBA",
        "Accuracy": 0.8,
        "Balance": 0.2,
        "LogLoss": 0.5394,
        "Brier": 0.1753,
        "ROI": 0.5273,
        "Samples": 5,
    },
    {
        "Period": "6m",
        "Split": "NBA - points",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5778,
        "Brier": 0.1935,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "6m",
        "Split": "NBA - rebounds",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.3857,
        "Brier": 0.1024,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "6m",
        "Split": "WNBA",
        "Accuracy": 0.5,
        "Balance": -0.5,
        "LogLoss": 0.7887,
        "Brier": 0.2953,
        "ROI": -0.0455,
        "Samples": 2,
    },
    {
        "Period": "6m",
        "Split": "WNBA - points",
        "Accuracy": 0.5,
        "Balance": -0.5,
        "LogLoss": 0.7887,
        "Brier": 0.2953,
        "ROI": -0.0455,
        "Samples": 2,
    },
    {
        "Period": "1y",
        "Split": "All",
        "Accuracy": 0.7143,
        "Balance": 0.0,
        "LogLoss": 0.6106,
        "Brier": 0.2096,
        "ROI": 0.3636,
        "Samples": 7,
    },
    {
        "Period": "1y",
        "Split": "All, Book Filtered",
        "Accuracy": 0.6667,
        "Balance": 0.0,
        "LogLoss": 0.6244,
        "Brier": 0.2165,
        "ROI": 0.2727,
        "Samples": 6,
    },
    {
        "Period": "1y",
        "Split": "NBA",
        "Accuracy": 0.8,
        "Balance": 0.2,
        "LogLoss": 0.5394,
        "Brier": 0.1753,
        "ROI": 0.5273,
        "Samples": 5,
    },
    {
        "Period": "1y",
        "Split": "NBA - points",
        "Accuracy": 0.75,
        "Balance": 0.25,
        "LogLoss": 0.5778,
        "Brier": 0.1935,
        "ROI": 0.4318,
        "Samples": 4,
    },
    {
        "Period": "1y",
        "Split": "NBA - rebounds",
        "Accuracy": 1.0,
        "Balance": 0.0,
        "LogLoss": 0.3857,
        "Brier": 0.1024,
        "ROI": 0.9091,
        "Samples": 1,
    },
    {
        "Period": "1y",
        "Split": "WNBA",
        "Accuracy": 0.5,
        "Balance": -0.5,
        "LogLoss": 0.7887,
        "Brier": 0.2953,
        "ROI": -0.0455,
        "Samples": 2,
    },
    {
        "Period": "1y",
        "Split": "WNBA - points",
        "Accuracy": 0.5,
        "Balance": -0.5,
        "LogLoss": 0.7887,
        "Brier": 0.2953,
        "ROI": -0.0455,
        "Samples": 2,
    },
]

_EXPECTED_CALIBRATION = [
    {"Bin": "(0.5, 0.55]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {
        "Bin": "(0.55, 0.6]",
        "Predicted": 0.5866666666666666,
        "Actual": 0.6666666666666666,
        "Count": 3,
    },
    {"Bin": "(0.6, 0.65]", "Predicted": 0.63, "Actual": 0.6666666666666666, "Count": 3},
    {"Bin": "(0.65, 0.7]", "Predicted": 0.68, "Actual": 1.0, "Count": 1},
    {"Bin": "(0.7, 0.75]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {"Bin": "(0.75, 0.8]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {"Bin": "(0.8, 0.85]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {"Bin": "(0.85, 0.9]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {"Bin": "(0.9, 0.95]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
    {"Bin": "(0.95, 1.0]", "Predicted": float("nan"), "Actual": float("nan"), "Count": 0},
]

_EXPECTED_ROI = [
    {"Period": "7d", "Threshold": 0.55, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "7d",
        "Threshold": 0.55,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "30d", "Threshold": 0.55, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "30d",
        "Threshold": 0.55,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "3m", "Threshold": 0.55, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "3m",
        "Threshold": 0.55,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "6m", "Threshold": 0.55, "Filter": "All", "Bets": 7, "Win%": 0.7143, "ROI": 0.3636},
    {
        "Period": "6m",
        "Threshold": 0.55,
        "Filter": "Book Filtered",
        "Bets": 6,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "1y", "Threshold": 0.55, "Filter": "All", "Bets": 7, "Win%": 0.7143, "ROI": 0.3636},
    {
        "Period": "1y",
        "Threshold": 0.55,
        "Filter": "Book Filtered",
        "Bets": 6,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "7d", "Threshold": 0.58, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "7d",
        "Threshold": 0.58,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "30d", "Threshold": 0.58, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "30d",
        "Threshold": 0.58,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "3m", "Threshold": 0.58, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "3m",
        "Threshold": 0.58,
        "Filter": "Book Filtered",
        "Bets": 4,
        "Win%": 0.75,
        "ROI": 0.4318,
    },
    {"Period": "6m", "Threshold": 0.58, "Filter": "All", "Bets": 7, "Win%": 0.7143, "ROI": 0.3636},
    {
        "Period": "6m",
        "Threshold": 0.58,
        "Filter": "Book Filtered",
        "Bets": 6,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "1y", "Threshold": 0.58, "Filter": "All", "Bets": 7, "Win%": 0.7143, "ROI": 0.3636},
    {
        "Period": "1y",
        "Threshold": 0.58,
        "Filter": "Book Filtered",
        "Bets": 6,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "7d", "Threshold": 0.6, "Filter": "All", "Bets": 3, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "7d",
        "Threshold": 0.6,
        "Filter": "Book Filtered",
        "Bets": 3,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "30d", "Threshold": 0.6, "Filter": "All", "Bets": 3, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "30d",
        "Threshold": 0.6,
        "Filter": "Book Filtered",
        "Bets": 3,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "3m", "Threshold": 0.6, "Filter": "All", "Bets": 3, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "3m",
        "Threshold": 0.6,
        "Filter": "Book Filtered",
        "Bets": 3,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "6m", "Threshold": 0.6, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "6m",
        "Threshold": 0.6,
        "Filter": "Book Filtered",
        "Bets": 5,
        "Win%": 0.8,
        "ROI": 0.5273,
    },
    {"Period": "1y", "Threshold": 0.6, "Filter": "All", "Bets": 5, "Win%": 0.8, "ROI": 0.5273},
    {
        "Period": "1y",
        "Threshold": 0.6,
        "Filter": "Book Filtered",
        "Bets": 5,
        "Win%": 0.8,
        "ROI": 0.5273,
    },
    {"Period": "7d", "Threshold": 0.65, "Filter": "All", "Bets": 2, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "7d",
        "Threshold": 0.65,
        "Filter": "Book Filtered",
        "Bets": 2,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "30d", "Threshold": 0.65, "Filter": "All", "Bets": 2, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "30d",
        "Threshold": 0.65,
        "Filter": "Book Filtered",
        "Bets": 2,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "3m", "Threshold": 0.65, "Filter": "All", "Bets": 2, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "3m",
        "Threshold": 0.65,
        "Filter": "Book Filtered",
        "Bets": 2,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "6m", "Threshold": 0.65, "Filter": "All", "Bets": 3, "Win%": 0.6667, "ROI": 0.2727},
    {
        "Period": "6m",
        "Threshold": 0.65,
        "Filter": "Book Filtered",
        "Bets": 3,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "1y", "Threshold": 0.65, "Filter": "All", "Bets": 3, "Win%": 0.6667, "ROI": 0.2727},
    {
        "Period": "1y",
        "Threshold": 0.65,
        "Filter": "Book Filtered",
        "Bets": 3,
        "Win%": 0.6667,
        "ROI": 0.2727,
    },
    {"Period": "7d", "Threshold": 0.7, "Filter": "All", "Bets": 1, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "7d",
        "Threshold": 0.7,
        "Filter": "Book Filtered",
        "Bets": 1,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "30d", "Threshold": 0.7, "Filter": "All", "Bets": 1, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "30d",
        "Threshold": 0.7,
        "Filter": "Book Filtered",
        "Bets": 1,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "3m", "Threshold": 0.7, "Filter": "All", "Bets": 1, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "3m",
        "Threshold": 0.7,
        "Filter": "Book Filtered",
        "Bets": 1,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "6m", "Threshold": 0.7, "Filter": "All", "Bets": 1, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "6m",
        "Threshold": 0.7,
        "Filter": "Book Filtered",
        "Bets": 1,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
    {"Period": "1y", "Threshold": 0.7, "Filter": "All", "Bets": 1, "Win%": 1.0, "ROI": 0.9091},
    {
        "Period": "1y",
        "Threshold": 0.7,
        "Filter": "Book Filtered",
        "Bets": 1,
        "Win%": 1.0,
        "ROI": 0.9091,
    },
]


def _expected_daily() -> list[dict]:
    return [
        {
            "Date": _d(100),
            "League": "NBA",
            "Market": "points",
            "Bets": 1,
            "Hits": 1,
            "Avg_Model_P": 0.61,
            "Profit": 0.9090909090909091,
        },
        {
            "Date": _d(100),
            "League": "WNBA",
            "Market": "points",
            "Bets": 1,
            "Hits": 0,
            "Avg_Model_P": 0.65,
            "Profit": -1.0,
        },
        {
            "Date": _d(3),
            "League": "NBA",
            "Market": "points",
            "Bets": 3,
            "Hits": 2,
            "Avg_Model_P": 0.6,
            "Profit": 0.8181818181818181,
        },
        {
            "Date": _d(3),
            "League": "NBA",
            "Market": "rebounds",
            "Bets": 1,
            "Hits": 1,
            "Avg_Model_P": 0.68,
            "Profit": 0.9090909090909091,
        },
        {
            "Date": _d(3),
            "League": "WNBA",
            "Market": "points",
            "Bets": 1,
            "Hits": 1,
            "Avg_Model_P": 0.59,
            "Profit": 0.9090909090909091,
        },
    ]


def _assert(actual: pd.DataFrame, expected: list[dict]) -> None:
    pd.testing.assert_frame_equal(
        actual.reset_index(drop=True), pd.DataFrame(expected), check_dtype=False
    )


def test_compute_individual_metrics_full_slate():
    hist_stats, daily, calibration, roi = compute_individual_metrics(_build())
    _assert(hist_stats, _EXPECTED_HIST)
    _assert(daily, _expected_daily())
    _assert(calibration, _EXPECTED_CALIBRATION)
    _assert(roi, _EXPECTED_ROI)


def test_compute_individual_metrics_empty_when_all_push():
    pushed = _build()
    pushed["Result"] = "Push"
    result = compute_individual_metrics(pushed)
    assert all(df.empty for df in result)
